### PR TITLE
fixing ipywidgets

### PR DESCRIPTION
**Pull request by choldgraf**
This is an attempt at fixing ipywidgets following the suggestions of @akhmerov...for some reason it still doesn't work though :-/

### CODE REVIEW

**Comment by akhmerov** [comment]
Still [this](https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/execute.py#L952-L959) to add?

**Comment by choldgraf** [comment]
@akhmerov i believe that is here: https://github.com/ExecutableBookProject/sphinx-notebook/blob/master/sphinx_notebook/__init__.py#L83

**Comment by akhmerov** [comment]
Uhhh, maybe [this](https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/execute.py#L844-L845) then? :)

**Comment by akhmerov** [comment]
Or otherwise did you verify that the notebook that you're converting has widget state metadata stored?

**Comment by choldgraf** [comment]
I believe it does -if I open it up in jupyterlab then the widgets pop back up. I added in the javascript code from the function you mentioned - that definitely should be there either way

**Comment by choldgraf** [comment]
ugh - OK I think I figured out what the problem is - bootstrap (loaded by the theme we're using) seems to be clashing with RequireJS (required by ipywidgets). It's not related to this codebase at all :-P

I opened up https://github.com/jupyter-widgets/ipywidgets/issues/2787 and https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/issues/93 to try and spot-check this.

@akhmerov do you know if anybody has gotten jupyter-sphinx to run on a bootstrap-based site?

**Comment by choldgraf** [comment]
Latest commit should get this working by switching themes to Alabaster, which doesn't have this problem. These docs aren't complex enough yet to warrant a theme like pydata anyway, so we can test on alabaster and spot-check the pydata them problem in another issue

**Pull request merged**
